/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TodoApp2;

import controller.ProjectController;
import controller.TaskController;
import java.sql.SQLException;
import java.util.Date;
import java.util.List;
import model.Project;
import model.Task;

public class App {

    //public String getGreeting() {
    //    return "Hello World!";
    //}
    public static void main(String[] args) throws SQLException {

        /*TaskController taskController = new TaskController();

    Task task = new Task();
    task.setId(1); // ID da tarefa que você deseja atualizar
    task.setIdProject(2); // ID do projeto ao qual a tarefa está associada
    task.setName("Novo nome da tarefa");
    task.setDescription("Nova descricao da tarefa");
    task.setNotes("Novas notas da tarefa");
    task.setCompleted(false);
    task.setDeadline(new Date());
    task.setUpdatedAt(new Date());

    taskController.update(task);
    
    List<Task> tasks = taskController.getAll(2);
    System.out.println("Total de tarefas = " + tasks.size());
    
    taskController.removeById(4);*/
    }

    //public static void main(String[] args) {
    //    System.out.println(new App().getGreeting());
    //}
}
